### ISSUE TITLE
Elevator Action Bootleg.

### ISSUE THREAD

**Issue by 2thVet** [antongale/arcade-taitosj#1]
### Ask a question about the IP Core

I have been able to get all of my other roms to function with this new core, except Elevator Action Bootleg...any suggestions as to the issue, it's weird, the rom size after converting the zip is always small, not 116 like all the other roms.

**Comment by antongale** [comment]
Sounds like the bootleg ROMs are not included in your ROM dump.

**Comment by 2thVet** [comment]
Fixed it when I used the pocket updater, and it updated this rom.

Thanks!

AT
